### ISSUE TITLE
(dev server) Slack app manifest APIs fail with `no_permission`

### ISSUE THREAD

**Issue by gr2m** [gr2m/github-app-slack-demo#32]
See the code at
https://github.com/gr2m/github-app-slack-demo/blob/01033c7f469847def39f38f4f35b5189ea20b1fe/dev/server.js#L114-L117

Once all `.env` variables are configured as described in [CONTRIBUTING.md](https://github.com/gr2m/github-app-slack-demo/blob/01033c7f469847def39f38f4f35b5189ea20b1fe/CONTRIBUTING.md), run `npm run dev`. It spawns `dev/server.js` in the background which is dynamically setting the webhook URLs of the GitHub App and Slack app to point to the `--live` URL form the local netlify server. But it's not working

https://github.com/gr2m/github-app-slack-demo/blob/01033c7f469847def39f38f4f35b5189ea20b1fe/dev/server.js#L114-L173

I couldn't figure out why. I would like to use the same APIs to programmatically register an app for local development, similar to what we do for the GitHub App: https://github.com/gr2m/github-app-slack-demo/blob/01033c7f469847def39f38f4f35b5189ea20b1fe/dev/scripts/register-github-app.js.

**Comment by stevengill** [comment]
Feels like an issue with the token. Are both prod and dev apps in the same workspace? And you are a collaborator on both?

**Comment by stevengill** [comment]
@gr2m any chance you can share your appID's with us?

**Comment by gr2m** [comment]
Hi @stevengill thanks for reaching out! The apps I'm using are

- local development: https://api.slack.com/apps/A07DBJVGQ59
- staging: https://api.slack.com/apps/A07D8UQ4TK7
- production: https://api.slack.com/apps/A07D8UUML2H

Happy to pair on this as well if that would be helpful? It'd be really nice to figure out

**Comment by stevengill** [comment]
@gr2m

1) Just want to confirm that token you are using belongs to you

2) can you rerun your app and cause the error again. We just want fresh logs in the backend here :)

**Comment by gr2m** [comment]
> * Just want to confirm that token you are using belongs to you

yes

> * can you rerun your app and cause the error again. We just want fresh logs in the backend here :)

Done :) 

Also - it just worked now 🤷🏼 I didn't change anything on my end. But I take it 😀 

Thank you so much for looking into it for for whatever magic seems to have resolved the problem.
Next I'll create a script to programmatically register a new slack app so the user doesn't have to do it manually. I'll let you know if I run into any more trouble.
