### ISSUE TITLE
Feature Listing

### ISSUE THREAD

**Issue by developertom01** [gr2m/github-app-slack-demo#4]
- List basic features to include 
- Approach to get them done

**Comment by gr2m** [comment]
Can you add more detail of what you want to do as part of this issue? Maybe share an example from a different project that you think would work well here?

**Comment by gr2m** [comment]
Can we close in favor of #17?

**Comment by gr2m** [comment]
sorry didn't mean to close it

**Comment by gr2m** [comment]
done via #15 and #29
