### ISSUE TITLE
Deploy to Netlify

### ISSUE THREAD

**Issue by developertom01** [gr2m/github-app-slack-demo#8]
- Configure entrypoint to be routed by Netlify functions
- Deploy to netlify

**Comment by gr2m** [comment]
Hey thanks for opening the issue! If you would like to give it a go, check out the these docs about how to create a node middleware: https://github.com/octokit/octokit.js?tab=readme-ov-file#webhooks

And these docs about what routes are exposed automatically for us:
https://github.com/octokit/octokit.js?tab=readme-ov-file#app-server

We will need to configure/set a webhook secret to make it work.

Other todos:

- [x] Setup Netlify for this repository (continuous deployment to https://github-app-slack-demo.netlify.app/)
- [ ] register a GitHub App and set webhooks URL to the netlify deployment
- [ ] Figure out how to receive webhooks from GitHub when running the local netlify dev server

This might also be useful as a reference. It's old and it uses Probot, but might have some useful insights:
https://github.com/probot/example-netlify-functions/

**Comment by gr2m** [comment]
Maybe, as a first step, create a function for a `GET /api/health` route that simply responds with `{"ok": true}`? We can use it for monitoring later and use it to play with the overall setup.
